services:
  jt-postgres:
    image: postgres:latest
    restart: unless-stopped
    user: postgres
    container_name: jt-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - jt-network
    env_file:
      - path: .env
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET not set}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL:?BETTER_AUTH_URL not set}
        BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS:?BETTER_AUTH_TRUSTED_ORIGINS not set}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
        POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER not set}
        POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB not set}
        POSTGRES_HOST: ${POSTGRES_HOST:?POSTGRES_HOST not set}
        POSTGRES_PORT: ${POSTGRES_PORT:?POSTGRES_PORT not set}
        DATABASE_URL: ${DATABASE_URL:?DATABASE_URL not set}
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID not set}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET not set}
        PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:?PUBLIC_BASE_URL not set}
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET not set}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:?BETTER_AUTH_URL not set}
      BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS:?BETTER_AUTH_TRUSTED_ORIGINS not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER not set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB not set}
      POSTGRES_HOST: ${POSTGRES_HOST:?POSTGRES_HOST not set}
      POSTGRES_PORT: ${POSTGRES_PORT:?POSTGRES_PORT not set}
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL not set}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID not set}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET not set}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:?PUBLIC_BASE_URL not set}
    ports:
      - '127.0.0.1:5173:5173'
    env_file:
      - path: .env
    networks:
      - jt-network
    depends_on:
      - jt-postgres
  workspace:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: jt-workspace
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET not set}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:?BETTER_AUTH_URL not set}
      BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS:?BETTER_AUTH_TRUSTED_ORIGINS not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER not set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB not set}
      POSTGRES_HOST: ${POSTGRES_HOST:?POSTGRES_HOST not set}
      POSTGRES_PORT: ${POSTGRES_PORT:?POSTGRES_PORT not set}
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL not set}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:?GITHUB_CLIENT_ID not set}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:?GITHUB_CLIENT_SECRET not set}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL:?PUBLIC_BASE_URL not set}
    env_file:
      - path: .env
    networks:
      - jt-network
    tty: true
    stdin_open: true
    depends_on:
      - jt-postgres

volumes:
  postgres-db:

networks:
  jt-network:
    driver: bridge
