services:
  jt-postgres:
    image: postgres:latest
    restart: unless-stopped
    user: postgres
    container_name: jt-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - jt-network
    env_file:
      - path: .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    env_file:
      - path: .env
    networks:
      - jt-network
    depends_on:
      - jt-postgres
  workspace:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: jt-workspace
    env_file:
      - path: .env
    networks:
      - jt-network
    tty: true
    stdin_open: true
    depends_on:
      - jt-postgres

volumes:
  postgres-db:

networks:
  jt-network:
    driver: bridge
